In [1]:
import pandas as pd
import numpy as np

In [2]:
diab = pd.read_csv(r'C:\Users\Hamada\Downloads\archive (16)\Dataset of Diabetes .csv')
diab.head(5)

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

In [3]:
diab.drop('ID', axis=1, inplace=True)

In [4]:
diab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No_Pation  1000 non-null   int64
 1   Gender     1000 non-null   object
 2   AGE        1000 non-null   int64
 3   Urea       1000 non-null   float64
 4   Cr         1000 non-null   int64
 5   HbA1c      1000 non-null   float64
 6   Chol       1000 non-null   float64
 7   TG         1000 non-null   float64
 8   HDL        1000 non-null   float64
 9   LDL        1000 non-null   float64
 10  VLDL       1000 non-null   float64
 11  BMI        1000 non-null   float64
 12  CLASS      1000 non-null   object
dtypes: float64(8), int64(3), object(2)
memory usage: 101.7+ KB

In [5]:
diab.duplicated().sum()

0

In [6]:
diab['CLASS'].value_counts()

CLASS
Y     840
N     102
P      53
Y       4
N       1
Name: count, dtype: int64

In [7]:
diab['Gender'] = diab['Gender'].map({'F': 0, 'M': 1})
diab['CLASS'] = diab['CLASS'].map({'N': 0, 'Y': 1 , 'P': 2 })

In [8]:
diab.head(5)

,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,17975,0.0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0.0
1,34221,1.0,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0
2,47975,0.0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0.0
3,87656,0.0,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,0.0
4,34223,1.0,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0

In [9]:
diab['CLASS'].value_counts()

CLASS
1.0    840
0.0    102
2.0     53
Name: count, dtype: int64

In [10]:
diab['CLASS'].isnull().sum()

5

In [11]:
diab.dropna(inplace=True)

In [12]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
x = diab.drop('CLASS', axis=1)
y = diab['CLASS']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
smote = SMOTE()
x_train, y_train = smote.fit_resample(x_train, y_train)

In [14]:
x_tr , x_val , y_tr , y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [15]:
std = StandardScaler()
x_tr_std = std.fit_transform(x_tr)
x_val_std = std.transform(x_val)
x_test_std = std.transform(x_test)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc , mean_absolute_error , mean_squared_error
from sklearn.metrics import r2_score

In [17]:
Log = LogisticRegression()
Log.fit(x_tr_std, y_tr)
y_pred = Log.predict(x_val_std)
print(accuracy_score(y_val, y_pred))
print(mean_absolute_error(y_val, y_pred))
print(mean_squared_error(y_val, y_pred))
print(r2_score(y_val, y_pred))

0.9675810473815462
0.04488778054862843
0.06982543640897755
0.8945945438500967

In [18]:
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor

In [19]:
DTC = DecisionTreeClassifier()
DTC.fit(x_tr_std, y_tr)
y_pred = DTC.predict(x_val_std)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(accuracy_score(y_val, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00       127
         1.0       0.99      1.00      1.00       135
         2.0       1.00      1.00      1.00       139

    accuracy                           1.00       401
   macro avg       1.00      1.00      1.00       401
weighted avg       1.00      1.00      1.00       401

[[126   1   0]
 [  0 135   0]
 [  0   0 139]]
0.9975062344139651

In [20]:
rfr = DecisionTreeRegressor()
rfr.fit(x_tr_std, y_tr)
y_pred = rfr.predict(x_val_std)
print(mean_absolute_error(y_val, y_pred))
print(mean_squared_error(y_val, y_pred))
print(r2_score(y_val, y_pred))

0.0024937655860349127
0.0024937655860349127
0.9962355194232178

In [21]:
from sklearn.ensemble import RandomForestClassifier , RandomForestRegressor

In [22]:
RFC = RandomForestClassifier()
RFC.fit(x_tr_std, y_tr)
y_pred = RFC.predict(x_val_std)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(accuracy_score(y_val, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       127
         1.0       1.00      1.00      1.00       135
         2.0       1.00      1.00      1.00       139

    accuracy                           1.00       401
   macro avg       1.00      1.00      1.00       401
weighted avg       1.00      1.00      1.00       401

[[127   0   0]
 [  0 135   0]
 [  0   0 139]]
1.0

In [23]:
RFR = RandomForestRegressor()
RFR.fit(x_tr_std, y_tr)
y_pred = RFR.predict(x_val_std)
print(mean_absolute_error(y_val, y_pred))
print(mean_squared_error(y_val, y_pred))
print(r2_score(y_val, y_pred))

0.0038653366583541143
0.0011234413965087282
0.9983041015001596

In [24]:
from xgboost import XGBClassifier , XGBRegressor

In [25]:
XGB = XGBClassifier()
XGB.fit(x_tr_std, y_tr)
y_pred = XGB.predict(x_val_std)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))
print(accuracy_score(y_val, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00       127
         1.0       0.99      1.00      1.00       135
         2.0       1.00      1.00      1.00       139

    accuracy                           1.00       401
   macro avg       1.00      1.00      1.00       401
weighted avg       1.00      1.00      1.00       401

[[126   1   0]
 [  0 135   0]
 [  0   0 139]]
0.9975062344139651

In [26]:
XGBR = XGBRegressor()
XGBR.fit(x_tr_std, y_tr)
y_pred = XGBR.predict(x_val_std)
print(mean_absolute_error(y_val, y_pred))
print(mean_squared_error(y_val, y_pred))
print(r2_score(y_val, y_pred))

0.0037329317861970576
0.0008510535628985735
0.9987152863824594

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
XGB_Grid = GridSearchCV(XGBClassifier(), param_grid={'max_depth': [2, 3, 4, 5], 'n_estimators': [50, 100, 150, 200]}, cv=5)
XGB_Grid.fit(x_tr_std, y_tr)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'max_depth': [2, 3, 4, 5],
                         'n_estimators': [50, 100, 150, 200]})

In [29]:
XGB_Grid.best_params_

{'max_depth': 4, 'n_estimators': 150}

In [30]:
XGB_Grid.best_score_

0.994378894080997

In [31]:
y_pred = XGB_Grid.predict(x_val_std)

In [32]:
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00       127
         1.0       0.99      1.00      1.00       135
         2.0       1.00      1.00      1.00       139

    accuracy                           1.00       401
   macro avg       1.00      1.00      1.00       401
weighted avg       1.00      1.00      1.00       401

[[126   1   0]
 [  0 135   0]
 [  0   0 139]]

In [34]:
diab.to_csv('diab.csv', index=False)

In [33]:
import joblib
joblib.dump(XGB_Grid, 'XGB_Grid.pkl')

['XGB_Grid.pkl']

In [ ]:
import streamlit as st
import pandas as pd
import joblib

st.title('Diabetes Prediction')

# Load your model and dataset
diab = pd.read_csv('diab.csv')
model = joblib.load('XGB_Grid.pkl')

# User chooses text option
gender_text = st.selectbox('Gender', ['F', 'M'])

# Convert text to 0 or 1 as in your dataset
gender_num = 0 if gender_text == 'F' else 1

AGE = st.number_input('AGE')
Urea = st.number_input('Urea')
Cr = st.number_input('Cr')
HbA1c = st.number_input('HbA1c')
Chol = st.number_input('Chol')
TG = st.number_input('TG')
HDL = st.number_input('HDL')
LDL = st.number_input('LDL')
VLDL = st.number_input('VLDL')
BMI = st.number_input('BMI')

if st.button('Predict'):
    # Pass the numeric gender to model
    prediction = model.predict([[gender_num, AGE, Urea, Cr, HbA1c, Chol, TG, HDL, LDL, VLDL, BMI]])
    if prediction == 0:
        st.write('The person is not diabetic')
    else:
        st.write('The person is diabetic')