In [1]:
import pandas as pd
import numpy as np

In [2]:
wine = pd.read_csv(r'C:\Users\Hamada\Downloads\archive (15)\wine_quality_classification.csv')
wine.head()

   fixed_acidity  residual_sugar  alcohol  density quality_label
0            9.3             6.4     13.6   1.0005          high
1           11.2             2.0     14.0   0.9912        medium
2           11.6             0.9      8.2   0.9935           low
3           12.9             6.6     12.7   1.0002           low
4           13.9            13.8     10.4   0.9942        medium

In [3]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fixed_acidity   1000 non-null   float64
 1   residual_sugar  1000 non-null   float64
 2   alcohol         1000 non-null   float64
 3   density         1000 non-null   float64
 4   quality_label   1000 non-null   object
dtypes: float64(4), object(1)
memory usage: 39.2+ KB

In [4]:
wine.duplicated().sum()

0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder

In [6]:
wine['quality_label'] = wine['quality_label'].map({'high':2 , 'medium':1 , 'low':0})

In [7]:
wine.head()

   fixed_acidity  residual_sugar  alcohol  density  quality_label
0            9.3             6.4     13.6   1.0005              2
1           11.2             2.0     14.0   0.9912              1
2           11.6             0.9      8.2   0.9935              0
3           12.9             6.6     12.7   1.0002              0
4           13.9            13.8     10.4   0.9942              1

In [8]:
x = wine.drop('quality_label' , axis = 1)
y = wine['quality_label']
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.3 , random_state = 0)

In [9]:
y_train.value_counts()

quality_label
1    257
2    229
0    214
Name: count, dtype: int64

In [10]:
from imblearn.over_sampling import SMOTE

In [11]:
sm = SMOTE()
x_train , y_train = sm.fit_resample(x_train , y_train)
x_tr , x_val , y_tr , y_val = train_test_split(x_train , y_train , test_size = 0.3 , random_state = 0)

In [13]:
std = StandardScaler()
x_tr = std.fit_transform(x_tr)
x_val = std.transform(x_val)

c:\Users\Hamada\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [14]:
from xgboost import XGBClassifier,XGBRegressor
model = XGBClassifier()
model.fit(x_tr , y_tr)
model.score(x_val , y_val)

0.39655172413793105

In [15]:
model = XGBRegressor()
model.fit(x_tr , y_tr)
model.score(x_val , y_val)

-0.01431279090914539

In [16]:
from sklearn.ensemble import RandomForestClassifier , RandomForestRegressor
model = RandomForestClassifier()
model.fit(x_tr , y_tr)
model.score(x_val , y_val)

0.38362068965517243

In [17]:
rfr = RandomForestRegressor()
rfr.fit(x_tr , y_tr)
rfr.score(x_val , y_val)

-0.016257989505093162

In [18]:
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor

In [19]:
dtc = DecisionTreeClassifier()
dtc.fit(x_tr , y_tr)
dtc.score(x_val , y_val)

0.3922413793103448

In [20]:
dtc = DecisionTreeRegressor()
dtc.fit(x_tr , y_tr)
dtc.score(x_val , y_val)

-1.1901430188290978